### ISSUE TITLE
Interested in test cases

### ISSUE THREAD

**Issue by akshayimocha** [rturner1989/FCC-25-5-Clock-React#1]
Hey Robert,
Writing in the issue section since I don't have your contact information.

I got to checkout your **25+5** Clock App from freecodeCamp Project Feedback forum.
I am a ReactJS learner myself. But interested from testing point of view.

I'd like to know how are you running your test cases ? Are there any test files you have written.
Would be happy if you point me that direction.

Thanks in advance. 
Cheers.
![image](https://user-images.githubusercontent.com/87979509/129930847-47632b64-b31e-4269-8902-6c85bcd420f7.png)

**Comment by rturner1989** [comment]
Hello,

I havent written any of my own test cases, I'm just using the script included from FreeCodeCamp to make sure I'm passing all tests required for the module. 

Thanks! 
Rob

**Comment by akshayimocha** [comment]
Thanks for sharing this information. Appreciate. And all the best for your future projects.
